### ISSUE TITLE
StreamingAPIのデコードエラー

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/MisskeyAndroidClient#155]
```
W/SocketImpl: デコードエラー msg:{"type":"channel","body":{"id":"8d20a736-2b12-439d-be5c-be99a952f67a","type":"note","body":{"id":"8lp2oiif5t","createdAt":"2021-05-12T13:38:19.191Z","userId":"8bku1pzti4","user":{"id":"8bku1pzti4","name":"Thor 🇳🇴","username":"thor","host":"pl.thj.no","avatarUrl":"https://nos3.arkjp.net/?url=https%3A%2F%2Fpl.thj.no%2Fmedia%2Fbf68fb5dbe1ca0151a262f5f7c1a99f89c487e2da5c3f1fd6adbb1b871ca31be.jpeg&thumbnail=1","avatarBlurhash":"yNIYC0pyyYt-%#o}J8TK%#.7NytlS5tQIUV?nhxsjEWBV?x]bHbcozM|Rjt6WBkCbHR-R-xuxuIURjxZoeofofNGoyWCt7M{bHofR*","avatarColor":null,"instance":{"name":"Pleroma","softwareName":"pleroma","softwareVersion":"2.3.0-1-gb221d77a","iconUrl":"https://pl.thj.no/favicon.png","faviconUrl":"https://pl.thj.no/favicon.png","themeColor":null},"emojis":[],"onlineStatus":"unknown"},"cw":null,"visibility":"public","renoteCount":0,"repliesCount":0,"reactions":{},"emojis":[],"fileIds":[],"files":[],"replyId":null,"renoteId":"8loy77x2cp","uri":"https://pl.thj.no/activities/498b3caf-e819-
W/SocketImpl:     at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:191)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:256)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:273)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:256)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:479)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
    	at kotlinx.serialization.inter
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:191)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:256)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:273)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:256)
        at jp.panta.misskeyandroidclient.streaming.ChannelEvent$$serializer.deserialize(Unknown Source:673)
        at jp.panta.misskeyandroidclient.streaming.ChannelEvent$$serializer.deserialize(events.kt:26)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readPolymorphicJson(TreeJsonDecoder.kt:32)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:73)
    	at kotlinx.serialization.json.internal.Streaming
```

**Comment by Kinoshita0623** [comment]
上記の件についてはFilePropertyDTOのPropertiesに問題があることがわかった
ファイルによっては、width, heightがnullになることがある。
