### ISSUE TITLE
強制終了する不具合

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/MisskeyAndroidClient#368]
```
W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=8; index=255
        at com.github.penfeizhou.animation.gif.decode.GifDecoder.read(GifDecoder.java:99)
        at com.github.penfeizhou.animation.gif.decode.GifDecoder.read(GifDecoder.java:26)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:299)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder$6.run(FrameSeqDecoder.java:280)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
I/FrameSeqDecoder:  Set state to RUNNING,cost 2
E/AndroidRuntime: FATAL EXCEPTION: FrameDecoderExecutor-0
    Process: jp.panta.misskeyandroidclient, PID: 23788
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Rect.width()' on a null object reference
        at com.github.penfeizhou.animation.gif.decode.GifDecoder.renderFrame(GifDecoder.java:113)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:505)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:36)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:60)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:310)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder$6.run(FrameSeqDecoder.java:280)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by pantasystem** [comment]
この投稿を表示した時にクラッシュする
https://misskey.io/notes/8vt5dsu91f
