### ISSUE TITLE
java.lang.ClassCastExceptionで落ちる

### ISSUE THREAD

**Issue by CyberRex0** [pantasystem/MisskeyAndroidClient#390]
アプリを起動すると必ずクラッシュしてしまう。
長い文章を折りたたむ機能で躓いているように見える。
ストレージ消去して再度ログインするが改善しなかった。

```
01-30 17:22:00.226  5317  5317 E AndroidRuntime: FATAL EXCEPTION: main
01-30 17:22:00.226  5317  5317 E AndroidRuntime: Process: jp.panta.misskeyandroidclient, PID: 5317
01-30 17:22:00.226  5317  5317 E AndroidRuntime: android.view.InflateException: Binary XML file line #45 in jp.panta.misskeyandroidclient:layout/item_note: Binary XML file line #93 in jp.panta.misskeyandroidclient:layout/item_simple_note: Error inflating class jp.panta.misskeyandroidclient.ui.components.AutoCollapsingLayout
01-30 17:22:00.226  5317  5317 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #93 in jp.panta.misskeyandroidclient:layout/item_simple_note: Error inflating class jp.panta.misskeyandroidclient.ui.components.AutoCollapsingLayout
01-30 17:22:00.226  5317  5317 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at jp.panta.misskeyandroidclient.ui.notes.view.TimelineListAdapter.onCreateViewHolder(TimelineListAdapter.kt:210)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at jp.panta.misskeyandroidclient.ui.notes.view.TimelineListAdapter.onCreateViewHolder(TimelineListAdapter.kt:25)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2119)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:794)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.View.layout(View.java:22863)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6389)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3477)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2945)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1959)01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8187)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:878)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:811)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:368)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7710)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
01-30 17:22:00.226  5317  5317 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.content.res.TypedArray cannot be cast to java.lang.AutoCloseable
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at jp.panta.misskeyandroidclient.ui.components.AutoCollapsingLayout.<init>(AutoCollapsingLayout.kt:50)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at jp.panta.misskeyandroidclient.ui.components.AutoCollapsingLayout.<init>(AutoCollapsingLayout.kt:42)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        at jp.panta.misskeyandroidclient.ui.components.AutoCollapsingLayout.<init>(AutoCollapsingLayout.kt:39)
01-30 17:22:00.226  5317  5317 E AndroidRuntime:        ... 100 more
```

【環境】
OS: Android 11
アプリバージョン: v2.11.0
端末: Sony Xperia 5

**Comment by pantasystem** [comment]
ご迷惑をおかけしています。
現在発生している不具合は次回アップデートで修正される予定です。
よろしくお願いします。
