### ISSUE TITLE
アンテナ編集画面でアンテナを削除するとNPEでクラッシュする

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/MisskeyAndroidClient#465]
```
java.lang.NullPointerException: 
  at com.android.internal.util.Preconditions.checkNotNull (Preconditions.java:157)
  at android.widget.Toast.getLooper (Toast.java:179)
  at android.widget.Toast.<init> (Toast.java:164)
  at android.widget.Toast.makeText (Toast.java:492)
  at android.widget.Toast.makeText (Toast.java:480)
  at jp.panta.misskeyandroidclient.AntennaEditorActivity.onCreate$lambda-2 (AntennaEditorActivity.kt:67)
  at jp.panta.misskeyandroidclient.AntennaEditorActivity.$r8$lambda$Qa64xTi3uwZ6K9qD73jSmAY_YDg (Unknown Source)
  at jp.panta.misskeyandroidclient.AntennaEditorActivity$$ExternalSyntheticLambda4.onChanged (Unknown Source:4)
  at jp.panta.misskeyandroidclient.util.eventbus.EventBus.handleEvent (EventBus.kt:49)
  at jp.panta.misskeyandroidclient.util.eventbus.EventBus.setEvent (EventBus.kt:17)
  at jp.panta.misskeyandroidclient.ui.antenna.viewmodel.AntennaEditorViewModel$removeRemote$1.invokeSuspend (AntennaEditorViewModel.kt:268)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.internal.LimitedDispatcher.run (LimitedDispatcher.kt:39)
  at kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:95)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)
```

**Comment by pantasystem** [comment]
ローカル環境
```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
    Process: jp.panta.misskeyandroidclient, PID: 31551
    java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
        at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:157)
        at android.widget.Toast.getLooper(Toast.java:179)
        at android.widget.Toast.<init>(Toast.java:164)
        at android.widget.Toast.makeText(Toast.java:492)
        at android.widget.Toast.makeText(Toast.java:480)
        at jp.panta.misskeyandroidclient.AntennaEditorActivity.onCreate$lambda-2(AntennaEditorActivity.kt:67)
        at jp.panta.misskeyandroidclient.AntennaEditorActivity.$r8$lambda$Qa64xTi3uwZ6K9qD73jSmAY_YDg(Unknown Source:0)
        at jp.panta.misskeyandroidclient.AntennaEditorActivity$$ExternalSyntheticLambda4.onChanged(Unknown Source:4)
        at jp.panta.misskeyandroidclient.util.eventbus.EventBus.handleEvent(EventBus.kt:49)
        at jp.panta.misskeyandroidclient.util.eventbus.EventBus.setEvent(EventBus.kt:17)
        at jp.panta.misskeyandroidclient.ui.antenna.viewmodel.AntennaEditorViewModel$removeRemote$1.invokeSuspend(AntennaEditorViewModel.kt:268)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
